language: python
python:
  - "3.9"

services:
  - mysql

env:
  global:
    - MYSQL_HOST=127.0.0.1
    - MYSQL_USER=root
    - MYSQL_PASSWORD=
    - MYSQL_DATABASE=test_db

before_install:
  - sudo mysql -e "CREATE DATABASE IF NOT EXISTS test_db;"

install:
  - pip install -r requirements.txt
  - pip install pytest mysql-connector-python selenium

script:
  # Integration Test (MySQL)
  - echo "Running MySQL integration test..."
  - python tests/integration/test_db_connection.py

  # End-to-End Test
  - echo "Running E2E tests..."
  - pytest tests/e2e/test_user_login.py
